### PR TITLE
fix: Restoring windows after GlazeWM has been forcefully closed

### PR DESCRIPTION
**Pull request by s-v-o**
I was trying to implement a restore after GlazeWM was forcefully closed (#79).

Currently only the managed windows (more precisely the window handle) are saved and when GlazeWM is restarted the ManagedWindowCommand is called again for them.

The layout or workspace is not restored, but the user can access the windows again after the restart.

I'm sure there's a better solution, but maybe this will do until someone comes up with a better one.

### CODE REVIEW

**Comment by lars-berger** [comment]
Just a heads up - waiting a bit to review this.

Another member is drafting up a way to do IPC, which opens up another approach of doing this. The idea is to have a separate watchdog process that does 2 things: it keeps track of which windows are managed, and on process kill, it'll ensure all managed windows are shown. One big advantage with doing it that way is the user wouldn't have to relaunch the WM to un-hide the windows. IPC will probably be merged in sometime soon and then it'll possible to test whether that alternate approach is actually gonna be feasible

**Comment by b1scu1t** [comment]
I got a couple bugs with this. 
It saves the managed windows in `~/.glazewm/managedWindows.json' as expected but it would show a warning message stating that 'the file is in use'.
It happens every time GlazeWM is (re) started until the file is manually removed. 
image
With that message, GlazeWM freezes/becomes unresponsive to all Window Events or Keypresses. 
No rules get applied either. It must be forcefully killed in Task Manager.

**Comment by b1scu1t** [comment]
> I hope this will work better for you. But as @lars-berger said, this is more of a workaround and will probably be solved with another solution.


@s-v-o A workaround is better than nothing!
Your merge works as expected, killing GlazeWM unexpectedly isn't as dangerous as before.
The hidden windows return when it is restarted.
I no longer have to painstakingly unhide windows with GuiPropView or WinLister; the experience is leagues better now!

**Comment by s-v-o** [comment]
There is a better workaround now, so I think this pull request could be closed without merging.

**Pull request closed without merging**
